# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
    - src/stage_01_get_data.py
    - src/utils/common.py
    - configs/config.yaml
    outs:
    - data/cat
    - data/dog

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_02_prepare_base_model.py
    - src/utils/common.py
    - src/utils/model.py
    - configs/config.yaml
    params:
    - IMAGE_SIZE
    - LEARNING_RATE
    outs:
    - artifacts/base_model/base_model.h5
    - artifacts/base_model/updated_base_model.h5

  prepare_callback:
    cmd: python src/stage_03_prepare_callback.py --config=configs/config.yaml
    deps:
    - src/stage_03_prepare_callback.py
    - src/utils/common.py
    - src/utils/callbacks.py
    - configs/config.yaml
    - params.yaml
    outs:
    - artifacts/callbacks/checkpoint_cb.cb
    - artifacts/callbacks/tensorboard_cb.cb

  train:
    cmd: python src/stage_04_train.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_04_train.py
    - src/utils/common.py
    - src/utils/model.py
    - src/utils/callbacks.py
    - src/utils/data_management.py
    - configs/config.yaml
    - artifacts/callbacks/checkpoint_cb.cb
    - artifacts/callbacks/tensorboard_cb.cb
    - artifacts/base_model/updated_base_model.h5
    - data/cat
    - data/dog
    params:
    - IMAGE_SIZE
    - BATCH_SIZE
    - AUGMENTATION
    - EPOCHS
    outs:
    - artifacts/model
    - artifacts/tensorboard_log_dir
    - artifacts/checkpoints